# Generated by Django 2.2.1 on 2020-02-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatmessages', '0002_auto_20190703_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_seen',
            field=models.BooleanField(default=False),
        ),
    ]
